### ISSUE TITLE
cannot import name json_encoder

### ISSUE THREAD

**Issue by alexmahan** [grow/grow-ext-editor#100]
Hi! Just trying to play around with this locally to get an idea of the capabilities of the editor, and I'm getting the following error when I try to `grow run` the project after installing the extension:
```
  File "/Users/alexmahan/git/content-edit/extensions/editor/editor_api.py", line 14, in <module>
    from grow.common import json_encoder
ImportError: cannot import name json_encoder
```
When I open `editor_api.py` locally, it seems that it can't find a number of the imports, although in Terminal it doesn't error until it hits that `json_encoder` line:
![Screen Shot 2020-09-17 at 3 50 28 PM](https://user-images.githubusercontent.com/140830/93536312-8f21e900-f8fd-11ea-8376-e54ae20d4a9a.png)

Just wondering if I missed something during installation? I followed the setup instructions for installation of the extension and it appears that the relevant files have been installed into the extensions folder.

Thank you.

**Comment by jeremydw** [comment]
Hi Alex! Apologies for this blip - the editor is only compatible with Grow 1x on Python 3. I recommend using Pipenv to get this working:

```
# Ensure you have pipenv with `brew install pipenv libyaml`
pipenv install grow==1.0.0a10
pipenv run grow install
pipenv run grow run
```

That should do the trick.

Some point soon I'll post up a comprehensive starter that includes the editor, but I believe the above should resolve the issue for you.

Let me know if you have trouble with Pipenv and I can help debug.

**Comment by alexmahan** [comment]
@jeremydw Thanks! I had a sneaking suspicion it might be a Python 3 thing, will give this a shot. Hope you're doing ok in the midst of this weird and difficult year.
