### ISSUE TITLE
Accept a list for preview_fields

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#110]
If we have a bunch of options fields.

```
  - type: textarea
    key:  title
    label: title
  - type: textarea
    key: body
    label: body
  - type: group
    key: chapter.cta
    label: Cta
    fields: !g.yaml /content/schemas/cta.yaml?cta
    preview_field: text
```

and set the `preview_field: title` but the editor omits the title, we end up with nothing to preview.

Could we do:
```
preview_fields:
- title
- body
```
in which, grow editor checks for title and then falls back to body if not found?

**Comment by Zoramite** [comment]
This can be used by providing a list for preview fields and it will use the first one with a value:

```
preview_fields:
- title
- value
```
