### ISSUE TITLE
Multiple Preview Fields

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#118]
A given module maybe have optional fields - such as a title and body.  

```
chapter:
    title: ''
    body: world
```

Can we define multiple preview_fields in order of preference so that if one is empty, it falls back to the next.

```
preview_field: chapter.title | chapter.body

or 

preview_fields: 
- chapter.title 
- chapter.body

```

**Comment by Zoramite** [comment]
Duplicate of #110
