### ISSUE TITLE
Toasts with event support

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#17]
- We need to communicate status by adding "toast" messages.
- Toast should appear in bottom left and disappear after 3 seconds, by default, but be controllable to persist.
- An external/wrapper program should be able to interface with toasts by dispatching an event to the window with the content of the toast (i.e. the HTML content of the toast, the style, and whether it should persist.)

Example flows:

1. User presses "Save"
1. Once the Save (and Commit) XHR is complete, show a toast with the latest commit hash (wrapper program will have this information)

**Comment by Zoramite** [comment]
I didn't put toasts directly into the editor. Instead the editor triggers events which can be used to show toasts as needed by eternal JS.
