### ISSUE TITLE
YAML serialization readability

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#20]
When YAML files make a round trip via the editor, the editor re-serializes the YAML content. This has a few negative side effects for the developer experience.

Specifically, keys are alphabetized.

```
- partial: hohoho
  title: xxxx
  cta: xxx
```

becomes

```
- cta: xxx
  partial: hohoho
  title: xxx
```

If possible, we should set a few rules in the YAML serializer to preserve some existing conventions we've followed.

- `$`-prefixed builtins should appear at the top of the file
- All top-level keys should appear before `partials`
- The `partial` key within the partial loop should be the first

**Comment by Zoramite** [comment]
I think it is good to work with those rules for the serialization. One of the other ideas that I has was try and compare what currently exists key wise and try and match it. But I'm not sure how much extra work that would be. Especially with lists.

**Comment by Zoramite** [comment]
Handling this by updating grow to organize the fields at a lower level: https://github.com/grow/grow/pull/1067
