### ISSUE TITLE
Can't toggle nested fields once they have been expanded

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#28]
Need to be able to toggle nested fields once they're clicked and expanded. Currently, when you expand a nested field you can't collapse it until you "collapse all" with the button.

![image](https://user-images.githubusercontent.com/646525/76031115-e6291900-5eeb-11ea-8e6f-b0070928086a.png)

**Comment by Zoramite** [comment]
Fixed by 304a1c04bdefbc16d081a6ddc205b3692f84ca7e
