### ISSUE TITLE
Better [object Object] handling

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#29]
Sometimes a developer may place a nested YAML structure into a field that is configured to just be a text field. This shows as `[object Object]`

Ideally the editor has some flexibility for this data inconsistency, and autogenerates a field based on the YAML structure and lets the user modify that information without destroying/clobbering the underlying data.

![image](https://user-images.githubusercontent.com/646525/76057932-d0d5de00-5f2f-11ea-9bae-c99684d284e5.png)

**Comment by jeremydw** [comment]
Also, speaking more generally, I think there should be a way to use the editor for sites that don't have any schemas configured yet. :) I think we should have a tab at the top (name TBD) to the effect of:

- Fields (what we have now)
- Structured (name TBD, but new - just an auto-generated structured editor based on the content of the YAML file)
- Raw (what we have now - the code editor)

Then websites would be compatible with our editor with zero developer work, and it would unlock easier editing for non-Git users.

**Comment by jeremydw** [comment]
- AutoGuess should also handle lists of `g.doc` and `g.yaml` fields a bit better. It should show the tag value as the `preview_field in the UI`, right now it is just blank.

![image](https://user-images.githubusercontent.com/646525/76169153-bf105880-6132-11ea-8125-65221d85593a.png)

**Comment by Zoramite** [comment]
I'm going to close this issue for now. We have much better support for previews. And the initial [Object] should only happen when there are issues with the schema vs data. Which we don't want to actually ignore since it shouldn't really work with it not matching the schema.
