### ISSUE TITLE
Additional field schema properties

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#32]
The schema should be able to:

- Provide a `placeholder` value that appears in the input field's `placeholder`
- Provide a `help` value that appears beneath the input field in the editor
- Specify whether a field is `required` (for now, this doesn't have to be validated on the server, just in the UI via a `required` field)
- Set a max length for text fields

**Comment by Zoramite** [comment]
I've added `placeholder` and `help` as part of every field.

The required and constraints will be done separately as a bigger validation initiative.
