### ISSUE TITLE
Deep-linking to fields for sharing with clients

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#41]
We often need to send links to clients to directly edit something. We should have the ability to deep link to specific fields, and when the deep link is sent - the field should be highlighted automatically. 

At this moment, I'm not sure what the UX/UI for this should be, but I think the core feature can be built and we can tweak the styles for the link and the highlight later.

**Comment by Zoramite** [comment]
Added the ability to add classes, but also need to enable the auto expansion of the lists if the field is in the list.
