### ISSUE TITLE
!g.string support

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#49]
While I largely expect we will phase out `!g.string` over time thanks to the editor, the editor should be compatible with it, similarly to how it works with `!g.yaml`.

Currently, `!g.string` shows `[object Object]`. This should show the reference to the string instead. Ideally the user can override it with a standard string if they want to make edits.

![image](https://user-images.githubusercontent.com/646525/78410985-facc0000-75c2-11ea-93b0-5cce9cd2eec6.png)

**Comment by Zoramite** [comment]
Improved the editor to work with `!g.string` constructors.

![image](https://user-images.githubusercontent.com/107076/78831695-4ad20a80-79a7-11ea-9c82-381d89190c6d.png)

Added in b11f01989df6e49e9fcbd88e55b74a784bb9cf81
