### ISSUE TITLE
Prevent dragging during field focus

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#72]
The editor drag / sorting is enabled when a field is in focus.  

However, this appears to prevent the user from highlighting text within the text field making editing a bit more difficult.

Can we disable the dragging when any field is in focus and then reenable it on blur?

**Comment by Zoramite** [comment]
Right now you can drag and drop by dragging from anyone in the list item... would it be better to make is to the drag and drop only works when using the drag handle icon?

**Comment by uxder** [comment]
I think a handle icon would work if that is easier.   I think the whole list being draggable also works but when the input field has focus, it makes it hard to select the text so whatever is simplest for now works.

**Comment by Zoramite** [comment]
I think our current drag/sorting works well, but if this is still an issue just reopen.
