### ISSUE TITLE
Default grow editor background to white

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#73]
The grow editor preview currently wraps the site preview in a grey background.

![screenshot 2020-05-27 at 9 43 55](https://user-images.githubusercontent.com/7152/82963745-9cd5fa80-9ffe-11ea-87c1-23a4ed9fb4bd.jpg)

This can be problematic because a site's module might have no background (transparent).  Outside the editor, this module would appear white but in the editor, the background becomes grey.

I think the grow editor preview background should default to white as browsers do.

**Comment by Zoramite** [comment]
Thanks, I'll update the preview pane to always be white, regardless of the rest of the editor design.
