### ISSUE TITLE
Improve autoguess field types for Google Cloud Storage URLs

### ISSUE THREAD

**Issue by jeremydw** [grow/grow-ext-editor#89]
If a string field's value starts with "https://storage.googleapis.com" and if its type is being autoguessed, make the field type a google image field so it can be uploaded.

In the below example, the highlighted field should be autoguessed to an uploadable field.

![image](https://user-images.githubusercontent.com/646525/87589002-6da44700-c699-11ea-8167-71928d0de0ee.png)

**Comment by Zoramite** [comment]
This should be in there already.
